### ISSUE TITLE
An option to disable increase filename

### ISSUE THREAD

**Issue by kefengdeng-ibboost** [KrekkieD/protractor-snapshot#3]
Is it possible to disable increase filename somehow? which generate a filename with space, it is really annoying to run the shell scripts deal with those files with space in the name.

**Comment by KrekkieD** [comment]
I can make it part of the configurable filename so you can specify your own format, would that work? If I allow the feature to be fully disabled I run into an issue where the file may exist, and some may desire a warning, some may desire an overwrite.

**Comment by kefengdeng-ibboost** [comment]
Yes. I really prefer your solution. A customized postfix would be great, such as it could be '_1' instead of ' (1)'.

**Comment by KrekkieD** [comment]
Fixed in version 0.4.0, which is published to NPM. `%increment%` is the variable for the increment value, default file structure is practically unchanged. You should be able to change the `basename` config property to strip any spaces. Let me know if something does not work for you.

**Comment by kefengdeng-ibboost** [comment]
Really appreciate what you have done. The new version works perfectly. 

BTW, I have a minor suggestion, which might not suitable for others, but just in case if someone else needs. If I don't use %increment% in `basename`, without a pre-clean action, the tool will throw an error because file already exists. It would be great if we can introduce an optional setting "preserver" with default value "true" (link protractor-html-screenshot-report does). So if we set "preserver" to be "false", and the existing snapshots would be overwritten every time. 

However, this suggestion is really minor. I do have a pre-clean action before run protractor testings. 

Thanks again for your great effort on this tool.

Cheers

**Comment by KrekkieD** [comment]
I understand your suggestion, I have the same experience. The tool does not know if you're only just starting your run, so it cannot decide when to clean the target folders. The increment is also required when you make multiple snapshots from within the same spec.

I have set up a `beforeLaunch` in my protractor config, in which I use `rimraf` to clean my target folders. Of course it may be a convenience to add two methods (one for images, one for source) that do this cleaning for you, so all that would be required is hooking up he functions instead of having to manage the rimraf implementation.

Sounds not too hard :) will have a look when I have a few minutes.

**Comment by KrekkieD** [comment]
Added!

**Comment by kefengdeng-ibboost** [comment]
Great work! That works perfectly. Many thanks!!
